# PYTHON REVIEW

## Basic Trial

In [ ]:
import os
print(os.getcwd())

In [157]:
cd /Users/wanghaoling/Documents

/Users/wanghaoling/Documents


In [ ]:
!jupyter notebook


[I 2025-02-10 16:30:48.865 ServerApp] Extension package aext_assistant took 0.1697s to import
[W 2025-02-10 16:30:48.875 ServerApp] aext_panels | error adding extension (enabled: True): The module 'aext_panels' could not be found (cannot import name 'AuthConfig' from 'anaconda_cloud_auth.client' (/opt/anaconda3/lib/python3.12/site-packages/anaconda_cloud_auth/client.py)). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 323, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 187, in __init__
        self._load_metadata()
      File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 202, in _load_metadata
        rais

In [ ]:
import shutil
shutil.move("ReviewL1-L5.ipynb", "/Users/wanghaoling/Desktop/pythonr/ReviewL1-L5.ipynb")

In [ ]:
import os
print(os.getcwd())

## L1 ESSENTIAL

### Interaction

In [11]:
name = input('Enter your name: ') 

Enter your name:  JENNY


In [13]:
type(name)

str

In [15]:
print (type(name))

<class 'str'>


### Variable

In [33]:
#Define the new variable
my_variable = 'Bob'

#Read the first character
my_variable[0]

#Re-assign the first character?
my_variable[0] = "H"

TypeError: 'str' object does not support item assignment

### String

In [35]:
string_1 = 'Good'
string_2 = " day"
string_3 = string_1 + string_2
print(string_3)
print('Hello ' + 'World')

Good day
Hello World


In [37]:
string_1 = 'Good'
string_2 = " day"
string_3 = string_1 + string_2
print(len(string_3))

8


In [39]:
my_string = 'Hello World'
print(my_string[4])

o


In [41]:
#Subset of Characters
my_string = 'Hello World'
print(my_string[4]) #characters at position 4
print(my_string[0:5]) #from start to position 5
print(my_string[2:len(my_string)]) #from position 2 to the end

o
Hello
llo World


In [43]:
#Repeating Strings
print('*' * 10)
print('Hi' * 10)

**********
HiHiHiHiHiHiHiHiHiHi


* string.split()

In [50]:
#Splitting Strings
title = 'The Good, The Bad, and the Ugly'
print('Source string:', title)
print('Split using a space')
print(title.split(' '))
print('Split using a comma')
print(title.split(','))

Source string: The Good, The Bad, and the Ugly
Split using a space
['The', 'Good,', 'The', 'Bad,', 'and', 'the', 'Ugly']
Split using a comma
['The Good', ' The Bad', ' and the Ugly']


* string.count()

In [53]:
my_string = 'Count, the number of spaces'
print("my_string.count(' '):", my_string.count(' '))

my_string.count(' '): 4


In [57]:
my_string = 'Count, the number of spaces'
print("my_string.count('c'):", my_string.count('c'))

my_string.count('c'): 1


* string.replace()

In [60]:
welcome_message = 'Hello World!'
print(welcome_message.replace("Hello", "Goodbye"))

Goodbye World!


* str()

In [65]:
#Converting Other Types into Strings
msg = 'Hello Lloyd you are ' + str(21)
print(msg)

Hello Lloyd you are 21


* == and !=

In [70]:
print('James' == 'James') 
print('James' == 'John') 
print('James' != 'John') 

True
False
True


* string.format(v1, v2,...)
* or use index
* or use named values

In [74]:
age = 20 
print("{} is {} years old".format(name, age))

JENNY is 20 years old


In [79]:
state = "USA"
print("{} is {} years old living in {}".format(name, age, state))

JENNY is 20 years old living in USA


In [82]:
# Can specify an index for the substitution
format_string = "Hello {1} {0}, you got {2}%"
print(format_string.format('Smith', 'Carol', 75))

Hello Carol Smith, you got 75%


In [86]:
# Can use named substitutions, order is not significant
format_string = "{artist} sang {song} in {year}"
print(format_string.format(artist='Paloma Faith', song='Guilty', year=2017))

Paloma Faith sang Guilty in 2017


### Numbers, Booleans, None

### Numbers

* Types of numbers
    * integers
    * floating point numebrs
    * complex numbers

Converting between types

* int()
convert a floating point number into an int

In [95]:
i = int(1.0)
i

1

* float() convert an integer into a float

In [105]:
int_value = 1
string_value = '1.5'
float_value = float(int_value)
print('int value as a float:', float_value)
print(type(float_value))
float_value = float(string_value)
print('string value as a float:', float_value)
print(type(string_value))

int value as a float: 1.0
<class 'float'>
string value as a float: 1.5
<class 'str'>


### Boolean

In [109]:
all_ok = True
print(all_ok)
all_ok = False
print(all_ok)
print(type(all_ok))

True
False
<class 'bool'>


* bool()  (&int()) translate between integer and boolean

In [114]:
print(int(True))
print(int(False))
print(bool(1))
print(bool(0))

1
0
True
False


### None

In [119]:
winner = None
print('winner:', winner)
print('winner is None:', winner is None)
print('winner is not None:', winner is not None)
print(type(winner))

winner: None
winner is None: True
winner is not None: False
<class 'NoneType'>


In [121]:
winner = True
print('winner:', winner)
print('winner is None:', winner is None)
print('winner is not None:', winner is not None)
print(type(winner))

winner: True
winner is None: False
winner is not None: True
<class 'bool'>


### Arithmetic operators

// integer division (ignore any remainder)

% Modulus only return any remainder

** exponent

others see the note and ppt

In [134]:
x = 0
x+=1 #x=x+1
print(x)

1


## L2 Flow of Control

### if statement

### basic if 

In [141]:
#A basic IF statement
num = int(input('Enter a number: '))
if num < 0:
    print(num, 'is negative')

Enter a number:  -9


-9 is negative


### if else

In [4]:
#A basic if-else statement
num = int(input('Enter yet another number: '))
if num < 0:
    print('Its negative')
else:
    print('Its not negative')

Enter yet another number:  10


Its not negative


### if-elif-else

In [14]:
#A basic if-elif-else statement
savings = float(input("Enter how much you have in savings: "))
if savings == 0:
    print("Sorry no savings")
elif savings < 0:
    print("You are joking")
elif savings < 500:
    print('Well done')
elif savings < 1000:
    print('Thats a tidy sum')
elif savings < 10000:
    print('Welcome Sir!')
elif savings > 10000:
    print("Brilliant!")
else:
    print('Thank you')

Enter how much you have in savings:  30000


Brilliant!


### if expression

In [1]:
#A basic IF expression
age = input('Enter your age:')
status = None
if (int(age) > 12) and int(age) < 20:
    status = 'teenager'
else:
    status = 'not teenager'
print(status)

Enter your age: 20


not teenager


### Iteration and Looping

### while loop

usually used when the number of $\Large{\textbf{times}}$ we need to repeat the block of code to execute is $\Large{\textbf{not known}}$

In [3]:
#A basic WHILE loop
count = 0
print('Starting')
while count < 100:
    print(count,' ',end=',') 
    count += 1 
print("Done") 

Starting
0  ,1  ,2  ,3  ,4  ,5  ,6  ,7  ,8  ,9  ,10  ,11  ,12  ,13  ,14  ,15  ,16  ,17  ,18  ,19  ,20  ,21  ,22  ,23  ,24  ,25  ,26  ,27  ,28  ,29  ,30  ,31  ,32  ,33  ,34  ,35  ,36  ,37  ,38  ,39  ,40  ,41  ,42  ,43  ,44  ,45  ,46  ,47  ,48  ,49  ,50  ,51  ,52  ,53  ,54  ,55  ,56  ,57  ,58  ,59  ,60  ,61  ,62  ,63  ,64  ,65  ,66  ,67  ,68  ,69  ,70  ,71  ,72  ,73  ,74  ,75  ,76  ,77  ,78  ,79  ,80  ,81  ,82  ,83  ,84  ,85  ,86  ,87  ,88  ,89  ,90  ,91  ,92  ,93  ,94  ,95  ,96  ,97  ,98  ,99  ,Done


### for loop

step a variable through a series of values until a given test is met

In [9]:
#A basic FOR loop
#Loop over a set of values in a range
print('Print out values in a range')
for i in range(0,10):
    print(i)
print('Done')

Print out values in a range
0
1
2
3
4
5
6
7
8
9
Done


* anonymous for loop

In [14]:
#Now use an 'anonymous' loop variable
for _ in range(0,10):
    print('.', end='')

..........

In [20]:
for _ in range(0,10):
    print('love', '', end='')

love love love love love love love love love love 

### break loop statement

The break statement allows a developer to alter the normal cycle of the loop based on some criteria which may not be predictable in advance

In [30]:
#Breaking a loop
print('Only print code if all iterations completed')
num = int(input('Enter a number to check for: '))
for i in range(0, 6):
    if i == num:
        break
    print(i, ' ', end='')
print('Done')

Only print code if all iterations completed


Enter a number to check for:  2


0  1  Done


### continue loop statement

Allows you to skip over part of a loop’s iteration for a particular value, but then to continue with the remaining values in the sequence.

In [34]:
#Continuing a loop
for i in range(0, 10):
    print(i, ' ', end='')
    if i % 2 == 1:
        continue
    print('hey its an even number')
    print('we love even numbers')
print('Done')

0  hey its an even number
we love even numbers
1  2  hey its an even number
we love even numbers
3  4  hey its an even number
we love even numbers
5  6  hey its an even number
we love even numbers
7  8  hey its an even number
we love even numbers
9  Done


## L3 Data Types and Structure

basic data structures
* tuples
* lists
* dictionaries
* sets

### tuples

two ways to write

In [49]:
t = (1, 2.5, 'data')
type(t)

tuple

In [51]:
t = 1, 2.5, 'data'
type(t)

tuple

Python uses $\Large{\textbf{zero-based numbering}}$

In [54]:
t = 1, 2.5, 'data'
t[2]
type(t[2])

str

In [56]:
type(t[1])

float

* build-in method

* t.count()

In [58]:
t.count('data')

1

In [64]:
t.count(1)

1

In [66]:
t=1,2.5,'data','data','data'

t.count('data')

3

* t.index()

In [72]:
t.index('data')

2

In [74]:
t.index(2.5)

1

### lists

In [79]:
l = [1, 2.5, 'data']
l[2]

'data'

the general expression of the function please see the notes and ppt

In [81]:
l[1]=3

In [83]:
l

[1, 3, 'data']

* build-in method

In [94]:
a = [1 for _ in range(100)]
a

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [106]:
a = [1 for _ in range(100)]
a[1:10:4]=5
a

TypeError: must assign iterable to extended slice

In [112]:
a[1:50:4] = [5] * len(a[1:50:4])
a

[1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [116]:
a.append(3)
a

[1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3]

In [124]:
a.count(1)

87

In [126]:
a.count(5)

13

In [128]:
a.count(3)

2

In [130]:
del a[2:40:2]
a

[1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3]

In [132]:
a.count(1)

68

In [134]:
a.count(5)

13

In [144]:
a.extend([5]) #extend() requires an iterable, so [5] works because it's a list.
a

[1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 5,
 5,
 5]

In [146]:
a.index(3)

81

In [152]:
a.index(3,82)

82

In [154]:
a.index(5)

1

In [158]:
a.index(5,82)

83

In [162]:
a.insert(4,10)
a

[1,
 5,
 1,
 5,
 10,
 10,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 5,
 5,
 5]

In [166]:
a.remove(3)
a

[1,
 5,
 1,
 5,
 10,
 10,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 5,
 5]

In [168]:
a.pop(9)

5

In [178]:
a.reverse()
a

[5,
 5,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 1,
 5,
 1,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 5,
 1,
 1,
 5,
 1,
 10,
 10,
 5,
 1,
 5,
 1]

In [176]:
b=[1,2,3,4,5,6,7,8,9]
b.reverse()
b

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [182]:
a.sort()
a

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 10,
 10]

In [188]:
a.sort(reverse= TRUE)
a

NameError: name 'TRUE' is not defined

In [192]:
a.sort(reverse=True)
a

[10,
 10,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

### Dictionaries

unordered and not sortable

In [226]:
d = { 'Name' : 'Angela Merkel', 'Country' : 'Germany', 'Profession' :
'Chancelor', 'Age' : 64 }
type(d)

dict

In [200]:
print(d['Name'], d['Age'])

Angela Merkel 64


* build-in methods

In [202]:
d.keys()

dict_keys(['Name', 'Country', 'Profession', 'Age'])

In [204]:
d.values()

dict_values(['Angela Merkel', 'Germany', 'Chancelor', 64])

In [206]:
d.items()

dict_items([('Name', 'Angela Merkel'), ('Country', 'Germany'), ('Profession', 'Chancelor'), ('Age', 64)])

In [214]:
d['Name']

'Angela Merkel'

In [228]:
d['Name']='Jenny'
d

{'Name': 'Jenny', 'Country': 'Germany', 'Profession': 'Chancelor', 'Age': 64}

In [230]:
del d['Name']
d

{'Country': 'Germany', 'Profession': 'Chancelor', 'Age': 64}

In [232]:
d.clear()

In [234]:
d

{}

In [236]:
d = { 'Name' : 'Angela Merkel', 'Country' : 'Germany', 'Profession' :
'Chancelor', 'Age' : 64 }
c=d.copy()
c

{'Name': 'Angela Merkel',
 'Country': 'Germany',
 'Profession': 'Chancelor',
 'Age': 64}

In [244]:
d.popitem()

('Age', 64)

In [246]:
d.popitem()

('Profession', 'Chancelor')

In [258]:
e={'Gender','Female'}
d.update([e])
d

{'Name': 'Angela Merkel', 'Country': 'Germany', 'Gender': 'Female'}

### Sets

unordered collections of other objects, containing every element only once

In [264]:
s = set(['u', 'd', 'ud', 'du', 'd', 'du'])
s

{'d', 'du', 'u', 'ud'}

In [266]:
t = set(['d', 'dd', 'uu', 'u'])
t

{'d', 'dd', 'u', 'uu'}

In [268]:
#All of s and t.
s.union(t)

{'d', 'dd', 'du', 'u', 'ud', 'uu'}

In [270]:
#Items in both s and t.
s.intersection(t)

{'d', 'u'}

In [272]:
#Items in s but not in t.
s.difference(t)

{'du', 'ud'}

In [276]:
#Items in t but not in s.
t.difference(s)

{'dd', 'uu'}

In [278]:
#Items in t but not in s.
t.difference(s)

{'dd', 'uu'}

In [280]:
#Items in either s or t but not both.
s.symmetric_difference(t)

{'dd', 'du', 'ud', 'uu'}

### Arrays of Data

In [285]:
#basic array
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [287]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [291]:
m[1][0] #first row and second column

0.5

In [295]:
#Nesting
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [297]:
c[1][1][0]

1

* Numpy Array

In [3]:
#Import the numpy package
import numpy as np
#Create an ndarray object out of a list object with floats
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [308]:
type(a)

numpy.ndarray

In [310]:
#Create an ndarray object out of a list object with strs
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [312]:
#np.arange() works similar to range()
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [314]:
#… but takes as additional input the dtype parameter.
a = np.arange(8, dtype=np.float64)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

index of adarray

In [319]:
#With one-dimensional ndarray objects, indexing works as usual.
a[5:]

array([5., 6., 7.])

In [321]:
a[:2]

array([0., 1.])

* build-in methods

In [323]:
a.sum()

28.0

In [325]:
a.std()

2.29128784747792

In [327]:
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [333]:
#Scalar multiplication with list objects leads to a repetition of elements
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [335]:
#Working with ndarray objects implements a proper scalar multiplication
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [337]:
2*a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [339]:
#This calculates element-wise the square values.
a**2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [341]:
#This interprets the elements of the ndarray as the powers
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [343]:
#This calculates the power of every element to itself.
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [345]:
#Calculates the square root for every element
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [347]:
#Let's compare it with the math library
import math
math.sqrt(a) #It doesn't work with arrays, only floats!

TypeError: only length-1 arrays can be converted to Python scalars

* For float operations, we want to use the math library!

In [350]:
import timeit
import_module_np = "import numpy as np"
print(timeit.timeit('np.sqrt(2.5)',setup=import_module_np))

0.36414341698400676


In [352]:
import timeit
import_module_math = "import math"
print(timeit.timeit('math.sqrt(2.5)',setup=import_module_math))

0.040500458009773865


* have the ndarray objects instantiated first 

In [369]:
c = np.zeros((2, 3), dtype='i', order='C')   #NumPy-specific data types for ndarray objects
#The order in which to store elements in memory: C for C-like (i.e., row-wise) or F for Fortran-like (i.e., column-wise)
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [361]:
d = np.ones_like(c, dtype='float16', order='C') # the shage of d is the same as c
d

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [365]:
e = np.empty((2, 3, 2)) #last2: 2 arrays
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

* reshaping: 
provides another view of the same data

In [373]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [375]:
g.shape

(15,)

In [377]:
np.shape(g)

(15,)

In [379]:
g.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [381]:
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [383]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

* resizing: creates a new (temporary) object

In [390]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [392]:
np.resize(g, (1, 5))

array([[0, 1, 2, 3, 4]])

In [394]:
np.resize(g, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

* Stacking

In [397]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [399]:
np.hstack((h, 2 * h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [413]:
j=np.arange(2,34,4)
j

array([ 2,  6, 10, 14, 18, 22, 26, 30])

In [427]:
k=j.reshape(2,4)
k

array([[ 2,  6, 10, 14],
       [18, 22, 26, 30]])

In [429]:
np.hstack((k, k/2))

array([[ 2.,  6., 10., 14.,  1.,  3.,  5.,  7.],
       [18., 22., 26., 30.,  9., 11., 13., 15.]])

In [431]:
np.vstack((k, k/2))

array([[ 2.,  6., 10., 14.],
       [18., 22., 26., 30.],
       [ 1.,  3.,  5.,  7.],
       [ 9., 11., 13., 15.]])

* Boolean Arrays

In [436]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [438]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [444]:
np.where(h > 7, 1, 0)  #True=1, False=0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [446]:
np.where(h > 7, 9, 3)  #True=9, False=3

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 9],
       [9, 9, 9],
       [9, 9, 9]])

* speed comparison

In [451]:
#Speed Comparison
import timeit
timeit.timeit("[random.gauss(0, 1) for j in range(5000)]", setup="import random", number=10)

0.02726691699353978

In [455]:
timeit.timeit("numpy.random.standard_normal((5000,1))", setup="import numpy", number=10)  #Generates a (5000 × 1) array

0.0031716660014353693

* np.eye(): generate identity matrix

In [9]:
import numpy as np
I = np.eye(4)  # 4x4 identity matrix
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Structured Arrays

Structured (and record) arrays allow the description and handling of table-like data structures with a variety of different data types per (named) column.

In [26]:
#The complex dtype is composed
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

`('Name', 'S10')` <br>
This defines a field named `"Name"` that stores strings (in byte format) with a maximum length of 10 characters. <br>
`'S10'` represents a string of up to 10 bytes.

### Basic Vectorization

add two NumPy arrays element-wise

In [15]:
import numpy as np
np.random.seed(100)

In [21]:
#Create an ndarray object with random numbers
r = np.arange(12).reshape((4, 3))
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
#Create a second ndarray object with random numbers
s = np.arange(12).reshape((4, 3))*0.5
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [29]:
r+s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [23]:
import numpy as np
np.random.seed(10)

In [25]:
q = np.arange(12).reshape((4, 3))
q

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

* broadcast

Combine objects of different shape within a single operation.

In [36]:
#During scalar addition, the scalar is broadcast and added to every element.
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

$\textcolor{red}{\textbf{Custom-defined Python functions work with ndarray objects as well.}}$

In [45]:
#simple Python function implementing a linear transform on parameter x.
def f(x):
    return 3 * x + 5

In [47]:
f(0.5)

6.5

In [49]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

## L4 Functions

### Defining functions

```python
def function_name(parameter1,parameter):
        """docstring"""
        statement
        statement(s)

In [56]:
def print_my_msg(msg):
        print(msg)

In [58]:
msg="good afternoon"
print_my_msg(msg)

good afternoon


In [60]:
def square(n):
        return n*n

In [62]:
square(9)

81

In [64]:
#Docstrings
def do_calculations(n1):
        """This function takes a number as parameter and computes two results:
        *The first result is the number squared
        *The second result is the number plus 5"""
        res1 = n1*n1
        res2 = n1 + 5
        return res1,res2

In [66]:
do_calculations(9)

(81, 14)

In [68]:
a,b=do_calculations(9)

In [70]:
a

81

In [72]:
b

14

### Function parameter

The parameter list contains a list of parameter names separated by a comma

In [77]:
def do_calculations(n1,n2):
        res1 = n1*n2
        res2 = n1 + n2 + 5
        return res1,res2

In [79]:
do_calculations(1,2)

(2, 8)

### Named arguments

In [82]:
def greeter(name,
        title = 'Dr',
        prompt = 'Welcome',
        message = 'Live Long and Prosper'):
    print(prompt, title, name, '-', message)

In [84]:
greeter(name = 'Nacho')

Welcome Dr Nacho - Live Long and Prosper


In [86]:
greeter(prompt='Hello', title='Professor', name = 'Nacho', ',', message)

SyntaxError: positional argument follows keyword argument (933499566.py, line 1)

`prompt='Hello'`, `title='Professor'`, and `name='Nacho'` are keyword arguments. <br>.
`','` and `message` are positional arguments placed after keyword arguments, which is not allowed in Python.

In [89]:
greeter('Nacho', prompt='Hello', title='Professor')

Hello Professor Nacho - Live Long and Prosper


### Arbitrary arguments

$\textcolor{red}{\textbf{To define a parameter list as being of arbitrary length, a
parameter is marked with an asterisk (*).}}$

In [95]:
def greeter_list(*args):
    for name in args:
        print('Welcome', name)

In [97]:
greeter_list('Jenny','Helen','Tom','Jerry')

Welcome Jenny
Welcome Helen
Welcome Tom
Welcome Jerry


### Positional and Keyword arguments

do not know exactly how many of either positional or keyword arguments are going to be provided

In [2]:
def my_function(*args,**kwargs):
    for arg in args:
        print('arg:', arg)
    for key in kwargs.keys():
        print('key:', key, 'has value: ', kwargs[key])

In [4]:
my_function('John', 'Denise', daughter='Phoebe', son='Adam')

arg: John
arg: Denise
key: daughter has value:  Phoebe
key: son has value:  Adam


In [6]:
my_function('Paul', 'Fiona', son_number_one='Andrew', son_number_two='James', daughter='Joselyn')

arg: Paul
arg: Fiona
key: son_number_one has value:  Andrew
key: son_number_two has value:  James
key: daughter has value:  Joselyn


only use one of the *args and <br>
**kwargs depending on your requirements

In [9]:
def named(**kwargs):
    for key in kwargs.keys():
        print('arg:', key, 'has value:', kwargs[key])
named(a=1, b=2, c=3)

arg: a has value: 1
arg: b has value: 2
arg: c has value: 3


### Anonymous function/ Lambda function

does not have a name and can only be used at the point that it is defined

``` python
lambda arguments: expression


`lambda`: The keyword to define an anonymous function. <br>
`arguments`: Input parameters (similar to function arguments). <br>
`expression`: A single-line expression that is evaluated and returned. <>

In [20]:
double = lambda i: i*i
print(double(10))

100


In [24]:
square = lambda a: a**2
print(square(5))

25


# Additional Note: Markdown

This is *italic* text.
This is **bold** text.
This is `monospace` text.

*hello world*

**hello world**

`hello world`

* Item 1
* Item 2
  * Sub-item 1


1. First item
2. Second item
   1. Sub-item 1


Create link
[Google](https://www.google.com)

use photo
![Python Logo](https://www.python.org/static/community_logos/python-logo.png)

Find where the document is

In [63]:
import os
print(os.getcwd())

/Users/wanghaoling/Desktop/Numerical_Methods_in_Economics


In [57]:
from pathlib import Path

# Specify the file name (relative path)
file_name = 'UoN_logo.png'

# Get the absolute path
absolute_path = Path(file_name).resolve()

print(f"The absolute path is: {absolute_path}")


The absolute path is: /Users/wanghaoling/Desktop/Numerical_Methods_in_Economics/UoN_logo.png


![nottingham]("/Users/wanghaoling/Desktop/Numerical_Methods_in_Economics/UoN_logo.png")

```python
def hello():
    print("Hello, World!")


```R
plot(x,y)  #Generate scatter plots, line plots or other two-way graphs for two vectors x and y
x <- c(1,3,4,7,8,9)
y <- c(0,3,6,9,7,8)
plot(x ,y)

# Some other useful skills with python

In [69]:
import webbrowser

# Open a website in the default web browser
webbrowser.open("https://www.google.com.hk/webhp")


True

In [76]:
pip install requests

Note: you may need to restart the kernel to use updated packages.


In [78]:
import requests

# Get the content of the website
response = requests.get("https://www.nottingham.edu.cn/en/humanities-and-social-sciences/schools-and-department/economics/people/listing.aspx")

# Print the content
print(response.text)


<!DOCTYPE html>
	<html lang="en-GB">

	<head><meta charset="utf-8"><title>
	Know our people - University of Nottingham Ningbo China
</title>
		<!-- Google Tag Manager -->
		<script>
			(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'\u0026l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-PPLLW9WC');
		</script>
		<!-- End Google Tag Manager -->
		
    
    
    
    <meta name="GENERATOR" content="Contensis CMS Version 15.0" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="viewport" content="width=device-width, initial-scale=1" />


<meta http-equiv="X-UA-Compatible" content="IE=edge" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><link href="/siteelements/stylesheets/2018-additional-styles.css?version=9585684" re

In [81]:
pip install selenium

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 1.6 MB/s eta 0:00:00a 0:00:010m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.3/486.3 kB 2.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 2.2 MB/s eta 0:00:00
  Attempting uninstall: attrs
    Found existing installation: attrs 23.1.0
    Uninstalling attrs-23.1.0:
      Successfully uninstalled attrs-23.1.0
Note: you may need to restart the kernel to use updated packages.


In [1]:
from selenium import webdriver

# Initialize the Safari WebDriver
driver = webdriver.Safari()

# Open the website
driver.get("https://research.nottingham.edu.cn/en/persons/chew-chua")

